---
title: "Saemix 4.0 - multiple responses"
author: "Emmanuelle"
date: "07/02/2022"
output:
  pdf_document: default
  html_document: default
---

# TODO list

- **TODO** 
  - interface to mkin ?
  - error messages to solve better ?
    - unable to find starting parameter values
    - add FAQ as to how to diagnose this
    - maybe need a predict function for these models
  - bookdown: https://github.com/saemixdevelopment/saemix_bookdown
    - case-studies for categorical data and RTTE data
      - simulate using R instead of mlx
    - move online or keep pdf/tex version ?
      - if move completely online, need to transform the LaTeX guide into a bookdown
      - copy on iame github
- examples
  - real example with TTE and RTTE data
  - real example with competitive risks
  - joint models
- documentation
  - error models
  - new defaults: no plot for conditional distribution
- github
  - get the hang of branches...
- add a simulation function to generate diagnostics and simulate from the fitted model
  - test if simulate function exists before creatign VPC/npde
  - add an option to add this function later

### Loading

#### aaa_generics.R TODO

- check generic definition of read
- check aliases for some internal functions

#### zzz.R

- check if the current version works or if we need to add date

### Classes

#### SaemixData

- check object validation
  - create testthat functions
- harmonise output messages across the package
  - no messages to be output to stdin by default
- new slot automatic in 3.0
  - normally allows automatic recognition and filling in arguments not given
  - $\square$ TODO: testthat function
  - also test validate.names()
- use is(x, "data.frame") instead of testing class(x)=="data.frame" (class may have more than 1 value)

#### SaemixModel

- main change in 3.0: added discrete response with a modelType argument
  - for joint models, will need some tweak (maybe as a vector of response types ?)
- new function validate_covariance.model
  - $\square$ TODO: change name to validate.covariance.model
  - check function (add testthat) and add documentation

#### SaemixRes

- $\text{\rlap{$\checkmark$}}\square$ check definition of ypred and ppred
  - ypred should be f(theta_MAP) and ppred should be E(f(theta))
  - checked and corrected

#### SaemixObject

- maybe change name saemix.simul to saemix.simulate
- $\square$ TODO: logLik.saemix, AIC.SaemixObject, BIC.SaemixObject
  - Maud made changes in the 2.4
  - but Johannes also made some changes in 3.0
  - $\text{\rlap{$\checkmark$}}\square$ TODO: add Johannes's changes to the 2.4 version **in fact** already in 2.4 but 
- options
  - $\square$ TODO: see CRAN for the rules (like for 2.4, in compute_LL.R)

### Computational functions

#### compute_LL.R

- check if alias ggq.mlx exists

#### func_aux.R

- modified combined error model
  - $\square$ TODO: add to documentation
- conditional distribution function split into 2 functions according to nature of the model
  - $\square$ TODO:  add to documentation
- check computation of compute.LLy

### func_FIM.R

- $\square$ TODO: secure the code for discrete data models (only compute LL by linearisation ? do not use altogether ?)
- $\square$ TODO: check cat and replace with message
  - check name of option to print out messages (maybe name of option changed)

### Main algorithm

#### main_initialiseMainAlgo.R

- $\square$ TODO: check cat and replace with message
  - check name of option to print out messages (maybe name of option changed)

#### main_estep.R

- check computation of compute.LLy now completely replacing the computation of U.y
- 4th kernel added (Laplacian kernel)
  - $\square$ TODO:  add default option (0 iterations)
  - $\square$ TODO:  add to documentation and recommendations
  
#### main_mstep.R

- check computation of sigma and influence of SA (nbiter.saemix changed to nbiter.sa)
  - $\square$ TODO: check
- $\square$ TODO: add Lucie's changes +++
  - ask Lucie to check afterwards

#### main.R

- $\square$ TODO: check cat and replace with message
  - check name of option to print out messages (maybe name of option changed)

### Parameters, Simulations
  
#### func_distcond.R

- commented out the plots for the moment
  - $\square$ TODO: add option to output the graphs
  
#### func_estimParam.R

- renamed the function to predict newdata as in 2.4 (also has an Roxygen documentation now)
  - copied the old file in newCode
  - $\square$ TODO: check that the code within is similar

#### func_simulations.R

- renamed simul.saemix in saemix.simul in 3.0 for consistency (all functions start with saemix and not end with it)
  - $\square$ TODO:  add to documentation and CHANGELOG

### Plots

- $\square$ TODO: check cat and replace with message
  - check name of option to print out messages (maybe name of option changed)

## New functions by Maud

### BIC criterion

- definition and computation included in SaemixObject (see above)
  - $\square$ TODO:  add to documentation and CHANGELOG

### Algorithm

- create a notebook to test the algorithm and integrate it
- add test example
  - $\square$ TODO:  add to documentation

### HMM

$\square$ TODO: check status with Maud
