---
title: "Test_SAEMIX_multi_réponse"
author: "moi xD (Lucas Bodelle)"
date: "2025-04-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
################ Chemins ####################
knitr::opts_knit$set(root.dir = dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
workDir <- getwd()
datDir <- file.path(workDir, "exemple_emmanuelle")

################ Importation des librairies et R files ####################

library(tidyverse)
library(Rcpp)

for (i in 1:2){
  fichiers = sort(list.files(path = "R" , pattern = "\\." , full.names = TRUE))
  sapply(fichiers,source)
}

fichiers_multi = list.files(path="R_multi", pattern = "\\." , full.names = TRUE)
  sapply(fichiers_multi,source)


source("gridfuncd_mean_PKPD_ver.R")
sourceCpp("saemix_modelPBPK_CPP.cpp")
source("SaemixModelPBPK_PKPD_ver_CPP.R")

######################## Model PKPD ##############################

# Modèle
modelPKPD<-function(psi,id,xidep) {
  ytype<-xidep$ytype
  dose<-xidep[,1]
  tim<-xidep[,2]
  ka<-psi[id,1]
  V<-psi[id,2]
  CL<-psi[id,3]
  Emax<-psi[id,4]
  EC50<-psi[id,5]
  k<-CL/V
  ypred<-dose*ka/(V*(ka-k))*(exp(-k*tim)-exp(-ka*tim))
  ypredPD<-Emax*ypred/(ypred+EC50)
  ypred[ytype==2]<-ypredPD[ytype==2]
  return(ypred)
}

# Modèle
modelPKPD.cpt<-function(psi,id,xidep) {
  ytype<-xidep$ytype
  dose<-xidep[,1]
  tim<-xidep[,2]
  ka<-psi[id,1]
  V<-psi[id,2]
  CL<-psi[id,3]
  ke0 <- psi[id,4]
  Emax<-psi[id,5]
  EC50<-psi[id,6]
  k<-CL/V
  ypred<-dose*ka/(V*(ka-k))*(exp(-k*tim)-exp(-ka*tim))
  ypred.site <-dose*ka*ke0/V * (exp(-ka*tim)/(k-ka)/(ke0-ka) + exp(-k*tim)/(ka-k)/(ke0-k) +
                                  exp(-ke0*tim)/(ka-ke0)/(k-ke0))
  ypredPD<-Emax*ypred.site/(ypred.site+EC50)
  ypred[ytype==2]<-ypredPD[ytype==2]
  return(ypred)
}


```

```{r}


###########################################################

          # Simulation Numéro 1

############################################################


data_sim1 = read.csv(file.path(datDir,"basicPKPD_Sim1.csv") , header = TRUE)

# paramètres mu 
psi_ini =  c(ka = 1, V = 20, CL = 2, Emax = 100, EC50 = 5)
x.grid05 <- gridfuncd(data= data_sim1, psi0=psi_ini, e.obj = 0.05 , class = "ytype" , model = modelPKPD)


saemix.model <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim1$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model=diag(1,5,5), # Matrice diagonale , pas de covariance entre les paramètres
				error.model = c("proportional" , "constant"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = TRUE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 


saemix.data <- saemixData(name.data=data_sim1,header=TRUE,sep=" ",                  na=NA,name.group=c("id"),name.predictors=c("dose","tim"), name.response=c("y"), name.X="time",
					units = list(x = "mg/L", y = "hr"),name.ytype = "ytype")


options <- list(seed=54333, map=F, fim=F, ll.is=F,
                nbiter.saemix = c(300,200), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=F,
		warnings=TRUE, directory = "Fit1")

time.beg1 <- Sys.time()
fit_sim1 =  saemix.multi(saemix.model, saemix.data, options)
time.end1 <- Sys.time()
time.fit1 <- time.end1-time.beg1

saemix.model.exact <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim1$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model=diag(1,5,5), # Matrice diagonale , pas de covariance entre les paramètres
				error.model = c("proportional" , "constant"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = FALSE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 

options <- list(seed=54333, map=F, fim=F, ll.is=F,
                nbiter.saemix = c(300,200), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=F,
		warnings=TRUE, directory = "exactFit1")

time.beg1 <- Sys.time()
fit_sim1.exact =  saemix.multi(saemix.model.exact, saemix.data, options)
time.end1 <- Sys.time()
time.exact1 <- time.end1-time.beg1

```

```{r}
###########################################################

          # Simulation Numéro 2

############################################################

data_sim2 = read.csv(file.path(datDir,"basicPKPD_Sim2.csv"), header = TRUE)

# paramètres mu 
psi_ini =  c(ka = 1, V = 20, CL = 2, Emax = 100, EC50 = 5)
x.grid05 <- gridfuncd(data= data_sim2, psi0=psi_ini, e.obj = 0.05 , class = "ytype", model = modelPKPD)


saemix.model <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim2$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model=diag(1,5,5), # Matrice diagonale , pas de covariance entre les paramètres
				error.model = c("proportional" , "constant"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = TRUE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 


saemix.data <- saemixData(name.data=data_sim2,header=TRUE,sep=" ",                  na=NA,name.group=c("id"),name.predictors=c("dose","tim"), name.response=c("y"), name.X="time",
					units = list(x = "mg/L", y = "hr"),name.ytype = "ytype")


options <- list(seed=54333, map=T, fim=T, ll.is=F,
                nbiter.saemix = c(300,200), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=T,
		warnings=TRUE, directory = "Fit2")

time.beg1 <- Sys.time()
fit_sim2 =  saemix.multi(saemix.model, saemix.data, options)
time.end1 <- Sys.time()
time.fit2 <- time.end1-time.beg1


```


```{r}
###########################################################

          # Simulation Numéro 3

############################################################


data_sim3 = read.csv("C:/Users/lukyl/3D Objects/SAEMIX_PBPK_LUCAS/exemple_emmanuelle/basicPKPD_Sim3.csv" , header = TRUE)

# paramètres mu 
psi_ini =  c(ka = 1, V = 20, CL = 2, Emax = 100, EC50 = 5)
x.grid05 <- gridfuncd(data= data_sim3, psi0=psi_ini, e.obj = 0.05 , class = "ytype", model = modelPKPD)


saemix.model <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim3$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model=diag(1,5,5), # Matrice diagonale , pas de covariance entre les paramètres
				error.model = c("combined" , "proportional"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = TRUE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 


saemix.data <- saemixData(name.data=data_sim3,header=TRUE,sep=" ",                  na=NA,name.group=c("id"),name.predictors=c("dose","tim"), name.response=c("y"), name.X="time",
					units = list(x = "mg/L", y = "hr"),name.ytype = "ytype")


options <- list(seed=54333, map=T, fim=T, ll.is=F,
                nbiter.saemix = c(300,100), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=T,
		warnings=TRUE, directory = "Fit3")

fit_sim3 =  saemix.multi(saemix.model, saemix.data, options)


```


```{r}
###########################################################

          # Simulation Numéro 4

############################################################

data_sim4 = read.csv("C:/Users/lukyl/3D Objects/SAEMIX_PBPK_LUCAS/exemple_emmanuelle/basicPKPD_Sim4.csv" , header = TRUE)

# paramètres mu 
psi_ini =  c(ka = 1, V = 20, CL = 2, Emax = 100, EC50 = 5)
x.grid05 <- gridfuncd(data= data_sim4, psi0=psi_ini, e.obj = 0.05 , class = "ytype", model = modelPKPD)

omega <- diag(1,5,5)
omega[5,3]<-omega[3,5]<- 1


saemix.model <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim4$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model= omega , # Matrice non diagonale
				error.model = c("proportional" , "constant"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = TRUE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 


saemix.data <- saemixData(name.data=data_sim4,header=TRUE,sep=" ",                  na=NA,name.group=c("id"),name.predictors=c("dose","tim"), name.response=c("y"), name.X="time",
					units = list(x = "mg/L", y = "hr"),name.ytype = "ytype")


options <- list(seed=54333, map=T, fim=T, ll.is=F,
                nbiter.saemix = c(300,100), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=T,
		warnings=TRUE, directory = "Fit2")

fit_sim4 =  saemix.multi(saemix.model, saemix.data, options)


```


```{r}
###########################################################

          # Simulation Numéro 5

############################################################


data_sim5 = read.csv("C:/Users/lukyl/3D Objects/SAEMIX_PBPK_LUCAS/exemple_emmanuelle/basicPKPD_Sim5.csv" , header = TRUE)

# paramètres mu 
psi_ini =  c(ka = 1, V = 20, CL = 2, Emax = 100, EC50 = 5)
x.grid05 <- gridfuncd(data= data_sim5, psi0=psi_ini, e.obj = 0.05 , class = "ytype", model = modelPKPD)

omega <- diag(1,5,5)
omega[5,3]<-omega[3,5]<- 1
omega[1,1] = 0



saemix.model <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim5$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model= omega , # Matrice non diagonale
				error.model = c("proportional" , "constant"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = TRUE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 


saemix.data <- saemixData(name.data=data_sim5,header=TRUE,sep=" ",                  na=NA,name.group=c("id"),name.predictors=c("dose","tim"), name.response=c("y"), name.X="time",
					units = list(x = "mg/L", y = "hr"),name.ytype = "ytype")


options <- list(seed=54333, map=T, fim=T, ll.is=F,
                nbiter.saemix = c(300,100), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=T,
		warnings=TRUE, directory = "Fit2")

fit_sim5 =  saemix.multi(saemix.model, saemix.data, options)

```


```{r}

###########################################################

          # Simulation Numéro 6

############################################################

data_sim6 = read.csv("C:/Users/lukyl/3D Objects/SAEMIX_PBPK_LUCAS/exemple_emmanuelle/basicPKPD_Sim6.csv" , header = TRUE)

dose <- c(100,300,1000)
data_sim6$dose = dose[2]
data_sim6$dose[data_sim6$id<16] = dose[1]
data_sim6$dose[data_sim6$id>35] = dose[3]

# j'ai changé les doses car elles ne correspondaient pas. 
# sur le data set c'est rep(c(100,300,1000) , each = 1) or le xidep qui a permis d'obtenir les données est celui au dessus
# En gardant le dataset erroné, on arrive pas à converger.


# paramètres mu 
psi_ini =  c(ka = 1, V = 20, CL = 2, Emax = 100, EC50 = 5)

x.grid05 <- gridfuncd(data=data_sim6, psi0=psi_ini, e.obj = 0.05 , class = "ytype", model = modelPKPD)


saemix.model <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim6$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model= diag(1,5,5) , # Matrice diag
				error.model = c("proportional" , "constant"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = TRUE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 


saemix.data <- saemixData(name.data=data_sim6,header=TRUE,sep=" ",                  na=NA,name.group=c("id"),name.predictors=c("dose","tim"), name.response=c("y"), name.X="time",
					units = list(x = "mg/L", y = "hr"),name.ytype = "ytype")


options <- list(seed=54333, map=T, fim=T, ll.is=F,
                nbiter.saemix = c(300,100), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=T,
		warnings=TRUE, directory = "Fit2")

fit_sim6 =  saemix.multi(saemix.model, saemix.data, options)
























```

```{r}

# Je suis entrain de debug - Lucas , problème avec les valeurs environ égales à 0


###########################################################

          # Simulation_cpt Numéro 1

############################################################

data_sim1_cpt = read.csv("C:/Users/lukyl/3D Objects/SAEMIX_PBPK_LUCAS/exemple_emmanuelle/effectCptPKPD_Sim1.csv" , header = TRUE)

psi_ini =  c( ka = 1 , V = 20, CL = 2 , ke0 =  log(2)/5, Emax =  100, EC50 =  5)

x.grid05 <- gridfuncd(data=data_sim1_cpt, psi0=psi_ini, e.obj = 0.05 , class = "ytype" , model = modelPKPD.cpt )


saemix.model <- saemixModelPBPK(psi0=psi_ini, 
                                x.grid=x.grid05,
                                simulations=unique(data_sim6$id), 
                                output=NULL,
				covariate.model = NULL  , 
				covariance.model= diag(1,5,5) , # Matrice diag
				error.model = c("proportional" , "constant"), # proportionnel pour PK et constant pour PD
				modeltype = c("structural","structural") , 
				model.interpolate = TRUE , # on utilise la  grille
				name.response = c("y1","y2") , 
				model = modelPKPD) # le model structural 


saemix.data <- saemixData(name.data=data_sim6,header=TRUE,sep=" ",                  na=NA,name.group=c("id"),name.predictors=c("dose","tim"), name.response=c("y"), name.X="time",
					units = list(x = "mg/L", y = "hr"),name.ytype = "ytype")


options <- list(seed=54333, map=T, fim=T, ll.is=F,
                nbiter.saemix = c(300,100), nbiter.sa=20,
                nmc.is = 5000, nu.is=5, r.is=1, nbdisplay=25,
                displayProgress=T, print.is=F, save.graphs=T,
		warnings=TRUE, directory = "Fit2")

fit_sim6 =  saemix.multi(saemix.model, saemix.data, options)


```

